"""Notifications — real events generated by scans and agent operations."""

from __future__ import annotations

import logging
from typing import Literal, Optional
from uuid import uuid4

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from ..middleware.auth import get_current_user
from ..services.db import get_pool

logger = logging.getLogger(__name__)
router = APIRouter(tags=["notifications"])

NotificationKind = Literal["scan", "apply", "undo", "tip", "system", "agent"]

# ─── Ensure table exists ──────────────────────────────────────────────────────

_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS notifications (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL,
    kind        TEXT NOT NULL,
    title       TEXT NOT NULL,
    body        TEXT NOT NULL,
    read        BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS notifications_user_created
    ON notifications (user_id, created_at DESC);
"""

_table_ready = False

async def ensure_table() -> None:
    global _table_ready
    if _table_ready:
        return
    pool = get_pool()
    await pool.execute(_TABLE_SQL)
    _table_ready = True


# ─── Schemas ──────────────────────────────────────────────────────────────────

class NotificationRecord(BaseModel):
    id: str
    kind: str
    title: str
    body: str
    read: bool
    created_at: str  # ISO string — simpler for JS


class NotificationsResponse(BaseModel):
    notifications: list[NotificationRecord]
    unread_count: int


# ─── Internal helper (called from other routers) ──────────────────────────────

async def create_notification(
    user_id: str,
    kind: NotificationKind,
    title: str,
    body: str,
) -> None:
    """Fire-and-forget: insert a notification row. Errors are logged, not raised."""
    try:
        await ensure_table()
        pool = get_pool()
        await pool.execute(
            """
            INSERT INTO notifications (user_id, kind, title, body)
            VALUES ($1, $2, $3, $4)
            """,
            user_id, kind, title, body,
        )
    except Exception as exc:
        logger.warning("Failed to create notification: %s", exc)


# ─── Routes ───────────────────────────────────────────────────────────────────

@router.get("/notifications", response_model=NotificationsResponse)
async def get_notifications(
    limit: int = 50,
    user: dict = Depends(get_current_user),
) -> NotificationsResponse:
    await ensure_table()
    user_id: str = user["sub"]
    pool = get_pool()

    rows = await pool.fetch(
        """
        SELECT id, kind, title, body, read, created_at
        FROM   notifications
        WHERE  user_id = $1
        ORDER  BY created_at DESC
        LIMIT  $2
        """,
        user_id, limit,
    )

    notifications = [
        NotificationRecord(
            id=str(r["id"]),
            kind=r["kind"],
            title=r["title"],
            body=r["body"],
            read=r["read"],
            created_at=r["created_at"].isoformat(),
        )
        for r in rows
    ]
    unread = sum(1 for n in notifications if not n.read)
    return NotificationsResponse(notifications=notifications, unread_count=unread)


@router.patch("/notifications/{notification_id}/read")
async def mark_read(
    notification_id: str,
    user: dict = Depends(get_current_user),
) -> dict:
    await ensure_table()
    pool = get_pool()
    result = await pool.execute(
        "UPDATE notifications SET read = NOT read WHERE id = $1 AND user_id = $2",
        notification_id, user["sub"],
    )
    if result == "UPDATE 0":
        raise HTTPException(status_code=404, detail="Notification not found")
    return {"ok": True}


@router.patch("/notifications/read-all")
async def mark_all_read(user: dict = Depends(get_current_user)) -> dict:
    await ensure_table()
    pool = get_pool()
    await pool.execute(
        "UPDATE notifications SET read = TRUE WHERE user_id = $1",
        user["sub"],
    )
    return {"ok": True}


@router.delete("/notifications/{notification_id}")
async def delete_notification(
    notification_id: str,
    user: dict = Depends(get_current_user),
) -> dict:
    await ensure_table()
    pool = get_pool()
    result = await pool.execute(
        "DELETE FROM notifications WHERE id = $1 AND user_id = $2",
        notification_id, user["sub"],
    )
    if result == "DELETE 0":
        raise HTTPException(status_code=404, detail="Notification not found")
    return {"ok": True}
